version: '0.2'
sources:
- database: local
  link: ''
  type: local
  branch: master
  cache_path: ''
  cache_timestamp: ''
  filters: null
- database: poo
  link: https://github.com/qxcodepoo/arcade.git
  type: clone
  branch: master
  cache_path: ''
  cache_timestamp: '2025-11-12 13:50:46'
  filters: []
expanded:
- poo@configuracao-e-aquecimento
- poo@campanha-principal
- poo@bloco_c-listas
- poo@bloco_d-crud-com-mapas-e-enumerações
- poo@bloco_f-herança-i
tasks: {}
flags:
  quests: 0
  tracks: 0
  tasks: 0
  graph: 0
  xray: 0
lang: py
selected: poo@budega
